### ISSUE TITLE
getting "date.getMonth()" is not a function error

### ISSUE THREAD

**Issue by mohanskumar** [eight04/angular-datetime#12]
Hi, getting "date.getMonth()" is not a function error when used with angular 1.4.8 any idea?

**Comment by eight04** [comment]
Could you create an example on [Plunker](https://plnkr.co)?

**Comment by instantaphex** [comment]
I'm running into a similar issue but with date.getTime() is not a function inside parser.setDate on line 825 of datetime.js.  It looks like somewhere during the digest cycle the date is being converted to a string instead of a Date object. When the parser gets ahold of it, it assumes that its a date object and tries to call date methods on it.

**Comment by eight04** [comment]
Did you use it with other input related modules?

**Comment by AmirGilboa** [comment]
same thing here. 
TypeError: date.getTime is not a function
datetime.js : 1524

i believe it is related to date format.
my date is taken from mongodb, and looks fine and works anywhere else.
this works:
Mon Oct 17 2016 09:52:31 GMT-0400 (Eastern Daylight Time)
this does not work:
1990-12-12T05:00:00.650Z

angular 1.5
if you have any idea, that would be great.

**Comment by eight04** [comment]
Make sure `ng-model` is a native JavaScript Date object.

**Comment by AmirGilboa** [comment]
thanks!
what solved my problem was the tip i got from another question here, https://github.com/eight04/angular-datetime/issues/15

and the line of code is this:
$scope.birthdate = moment($scope.user.birthdate).toDate();

so basically it's what you said: the date was not in the correct format, and moment is the best tool to fix that.

thanks everybody!
