### ISSUE TITLE
Any Way To Use Timezone Strings (UTC, EST)?

### ISSUE THREAD

**Issue by crazyjat** [eight04/angular-datetime#55]
I have an app that allows users to enter dates and times in either EST or UTC but I haven't been showing the timezone in the input field because I found no way to show it as the string instead of +0500.

A design change is needed to show the UTC or EST strings in the input field. Can this be done?

**Comment by eight04** [comment]
Our tokens are based on [Angular's date filter](https://docs.angularjs.org/api/ng/filter/date). There is no way to represent timezone as a string instead of an offset. Also, I don't think we should maintain the timezone string ourselves, including i18n.

I would suggest to create a `<select>` component to choose the timezone.

If you really need to put the timezone string into the input, I think we can allow developers to create customized token format, and let angular-datetime read it, like a plugin, then you can create your own token to represent timezone string. Also, you'll need to subclass `Date` to save timezone information in your date object.
